components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 4
        consumer-task-processor:
            thread_name: consumer
            worker_threads: 4
        producer-task-processor:
            thread_name: producer
            worker_threads: 4
    default_task_processor: main-task-processor

    components:
        handler-kafka-producers:
            path: /produce
            task_processor: main-task-processor
            method: POST
            producers_list:
              - kafka-producer-first
              - kafka-producer-second

        handler-kafka-consumer:
            path: /consume/{topic_name}
            task_processor: main-task-processor
            method: POST

        # /// [Kafka service sample - consumer static config]
        # yaml
        kafka-consumer:
            group_id: test-group
            topics:
              - test-topic-send
              - test-topic-consume-1
              - test-topic-consume-2
              - test-topic-consume-produced-1
              - test-topic-consume-produced-2
            auto_offset_reset: smallest
            max_batch_size: 10
            env_pod_name: HOSTNAME
            enable_auto_commit: false
            security_protocol: PLAINTEXT
            rd_kafka_custom_options:
                session.timeout.ms: 77000
                fetch.wait.max.ms: 1000
        # /// [Kafka service sample - consumer static config]

        # /// [Kafka service sample - producer static config]
        # yaml
        kafka-producer-first:
            delivery_timeout: 3000ms
            queue_buffering_max: 100ms
            poll_timeout: 10ms
            send_retries_count: 5
            enable_idempotence: true
            security_protocol: PLAINTEXT
            rd_kafka_custom_options:
                enable.gapless.guarantee: true
        # /// [Kafka service sample - producer static config]

        kafka-producer-second:
            delivery_timeout: 3000ms
            queue_buffering_max: 100ms
            enable_idempotence: true
            security_protocol: PLAINTEXT

        testsuite-support:

        http-client:
            fs-task-processor: main-task-processor

        tests-control:
            method: POST
            path: /tests/{action}
            skip-unregistered-testpoints: true
            task_processor: main-task-processor
            testpoint-timeout: 10s
            testpoint-url: $mockserver/testpoint
            throttling_enabled: false

        secdist: {}
        default-secdist-provider:
            config: /etc/kafka_service/secure_data.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        server:
            listener:
                port: 8187
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: "@stderr"
                    level: debug
                    overflow_behavior: discard

        dns-client:
            fs-task-processor: fs-task-processor
