components_manager:
    components:                       # Configuring components that were registered via component_list
        handler-db:
            path: /v1/db                  # Registering handler by URL '/v1/key-value'.
            task_processor: main-task-processor  # Run it on CPU bound task processor
            method: GET,POST
# /// [Clickhouse service sample - static config]
# yaml
        clickhouse-database:
            secdist_alias: clickhouse-database-alias
            initial_pool_size: 5
            max_pool_size: 10
            queue_timeout: 1s
            use_secure_connection: false
            compression: lz4
# /// [Clickhouse service sample - static config]

        secdist:                    # Component that stores configuration of hosts and passwords
            provider: default-secdist-provider
        default-secdist-provider:   # Component that loads configuration of hosts and passwords
            config: /etc/clickhouse_service/secure_data.json  # Values are supposed to be stored in this file
            missing-ok: true                             # ... but if the file is missing it is still ok
            environment-secrets-key: SECDIST_CONFIG      # ... values will be loaded from this environment value

        server:
            listener:                 # configuring the main listening socket...
                port: 8093            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stdout'
                    level: debug
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        dns-client:
            fs-task-processor: fs-task-processor

    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: 4         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: 4

    default_task_processor: main-task-processor  # Task processor in which components start.
