name: "CLA Assistant"
'on':
    issue_comment:
        types: [created]
    pull_request_target:
        types: [opened, closed, synchronize]

jobs:
    CLAssistant:
        runs-on: ubuntu-latest
        steps:
          - name: "CLA Assistant"
            if: startsWith(github.event.comment.body, 'I hereby agree to the terms
                of the CLA available at') || github.event_name == 'pull_request_target'
            uses: cla-assistant/github-action@v2.1.3-beta
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            with:
                path-to-signatures: 'userver.json'
                path-to-document: 'https://github.com/userver-framework/userver/blob/develop/CONTRIBUTING.md'
                branch: 'develop'
                remote-organization-name: userver-framework
                remote-repository-name: CLAs
                custom-pr-sign-comment: 'I hereby agree to the terms of the CLA available
                    at: https://yandex.ru/legal/cla/'
